FROM registry.access.redhat.com/ubi8/go-toolset:1.17.12

WORKDIR /workspace

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum

# Copy the go source
COPY main.go main.go
COPY api/ api/
COPY bundle/ bundle/
COPY config/ config/
COPY controllers/ controllers/
COPY scripts/ scripts/
