apiVersion: v1
kind: Pod
metadata:
  name: xjoin-validation-test
  namespace: test
spec:
  containers:
  - image: quay.io/ckyrouac/xjoin-validation:latest
    imagePullPolicy: Always
    name: xjoin-validation-test
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 64Mi
  restartPolicy: Never
