// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LogReader is an autogenerated mock type for the LogReader type
type LogReader struct {
	mock.Mock
}

// GetLogs provides a mock function with given fields: name, namespace
func (_m *LogReader) GetLogs(name string, namespace string) (string, error) {
	ret := _m.Called(name, namespace)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(name, namespace)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(name, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewLogReader interface {
	mock.TestingT
	Cleanup(func())
}

// NewLogReader creates a new instance of LogReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLogReader(t mockConstructorTestingTNewLogReader) *LogReader {
	mock := &LogReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
