apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: xjoin-controller-manager
  name: xjoin-operator-xjoin-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: xjoin-controller-manager
status:
  loadBalancer: {}
