apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "xjoin.cloud.redhat.com/v1alpha1",
          "kind": "XJoinPipeline",
          "metadata": {
            "name": "xjoinpipeline-sample"
          },
          "spec": {
            "connectCluster": "xjoin-kafka-connect-strimzi",
            "elasticSearchURL": "https://elasticsearch:9200"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: xjoin-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: XJoinPipeline is the Schema for the xjoinpipelines API
      displayName: XJoin Pipeline
      kind: XJoinPipeline
      name: xjoinpipelines.xjoin.cloud.redhat.com
      version: v1alpha1
  description: XJoin Operator to manage XJoin pipelines.
  displayName: xjoin-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - secrets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - kafka.strimzi.io
          resources:
          - kafkaconnectors
          - kafkaconnectors/finalizers
          verbs:
          - '*'
        - apiGroups:
          - xjoin.cloud.redhat.com
          resources:
          - xjoinpipelines
          - xjoinpipelines/finalizers
          - xjoinpipelines/status
          verbs:
          - '*'
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: xjoin-operator-xjoin-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: xjoin-controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: xjoin-controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                command:
                - /manager
                image: quay.io/cloudservices/xjoin-operator:66018b2
                name: manager
                resources:
                  limits:
                    cpu: 100m
                    memory: 30Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - xjoin
  links:
  - name: Xjoin Operator
    url: https://xjoin-operator.domain
  maturity: alpha
  provider:
    name: xjoin
  version: 0.0.1
