---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apicurio
  name: apicurio
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 10001
      protocol: TCP
      targetPort: 10000
      name: external
  selector:
    pod: xjoin-apicurio-service
  sessionAffinity: None
  type: ClusterIP
