---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: xjoin-elasticsearch
spec:
  http:
    service:
      metadata:
        creationTimestamp: null
      spec: {}
    tls:
      selfSignedCertificate:
        disabled: true
  version: 7.13.0
  nodeSets:
    - name: default
      podTemplate:
        spec:
          volumes:
            - name: elasticsearch-data
              emptyDir: {}
          containers:
            - name: elasticsearch
              resources:
                limits:
                  cpu: 1
                  memory: 2Gi
                requests:
                  cpu: 250m
                  memory: 1Gi
      count: 1
      config:
        node.store.allow_mmap: false
