apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: xjoin-elasticsearch
spec:
  version: 7.1.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false