apiVersion: v1
data:
  endpoint: aHR0cDovL3hqb2luLWVsYXN0aWNzZWFyY2gtZXMtZGVmYXVsdC54am9pbi1vcGVyYXRvci1wcm9qZWN0LnN2Yzo5MjAw
  username: eGpvaW4=
  password: eGpvaW4xMzM3
kind: Secret
metadata:
  name: xjoin-elasticsearch
type: Opaque
