---
apiVersion: batch/v1
kind: Job
metadata:
  name: inventory-migration
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - command:
        - /opt/app-root/bin/python
        - manage.py
        - db
        - upgrade
        env:
        - name: SQLALCHEMY_ENGINE_LOG_LEVEL
          value: INFO
        - name: INVENTORY_DB_HOST
          valueFrom:
            secretKeyRef:
              key: db.host
              name: host-inventory-db
        - name: INVENTORY_DB_USER
          valueFrom:
            secretKeyRef:
              key: db.user
              name: host-inventory-db
        - name: INVENTORY_DB_PASS
          valueFrom:
            secretKeyRef:
              key: db.password
              name: host-inventory-db
        - name: INVENTORY_DB_NAME
          value: insights
        - name: INVENTORY_LOG_LEVEL
          value: debug
        - name: KAFKA_TOPIC
          value: platform.system-profile
        - name: KAFKA_GROUP
          value: inventory
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: xjoin-kafka-cluster-kafka-bootstrap:9092
        - name: KAFKA_HOST_INGRESS_TOPIC
          value: platform.inventory.host-ingress
        - name: KAFKA_HOST_INGRESS_GROUP
          value: inventory-mq
        - name: KAFKA_SECONDARY_TOPIC_ENABLED
          value: "false"
        - name: KAFKA_HOST_EGRESS_TOPIC
          value: platform.inventory.events
        image: quay.io/cloudservices/insights-inventory:635f6d4
        imagePullPolicy: IfNotPresent
        name: inventory-migration
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi

---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: xjoin-kafka-cluster
  name: platform.inventory.host-ingress
  namespace: xjoin-operator-project
spec:
  partitions: 1
  replicas: 1
  topicName: platform.inventory.host-ingress

---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: xjoin-kafka-cluster
  name: platform.inventory.events
  namespace: xjoin-operator-project
spec:
  partitions: 1
  replicas: 1
  topicName: platform.inventory.events

---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: xjoin-kafka-cluster
  name: platform.system-profile
  namespace: xjoin-operator-project
spec:
  partitions: 1
  replicas: 1
  topicName: platform.system-profile