---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xjoin-operator-prometheus
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  verbs:
  - create
  - patch
  - get
  - watch
  - list
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xjoin-operator-prometheus-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xjoin-operator-prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: test
