apiVersion: v1
data:
  standard.interval: '120'
  validation.interval: '1800'
  validation.attempts.threshold: '2'
  validation.percentage.threshold: '5'
  init.validation.interval: '60'
  init.validation.attempts.threshold: '30'
  init.validation.percentage.threshold: '5'
  connect.cluster: xjoin-kafka-connect-strimzi
  kafka.cluster: xjoin-kafka-cluster
  elasticsearch.connector.tasks.max: '5'
kind: ConfigMap
metadata:
  name: xjoin