{
 "title": "XJoinOperator",
 "tags": [
  "platform-health",
  "xjoin"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Count Inconsistency (absolute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(xjoin_count_inconsistency_total)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "ID Inconsistency (absolute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(xjoin_id_inconsistency_total)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Full Inconsistency (absolute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(xjoin_full_inconsistency_total)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Host Count in ElasticSearch",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(xjoin_hosts_total)" }
   ]
  },
  {
   "title": "Validation Failure Rate [5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(xjoin_validation_failed_total[5m]))"
    }
   ]
  },
  {
   "title": "Refresh Rate [5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(xjoin_refresh_total[5m]))"
    }
   ]
  },
  { "title": "Operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Reconciliation time (validator)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"xjoin-validation\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Reconciliation time (controller)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"xjoin-controller\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Reconciliation rate [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total[1m])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  }
 ]
}