apiVersion: v1
kind: Template
metadata:
  name: kafka-user

parameters:
  - name: GROUP_ID
    value: xjoin
  - name: CONNECTOR_GROUP_PREFIX
    value: connect-xjoin
  - name: KAFKA_CLUSTER
    value: platform-mq

objects:
  - apiVersion: kafka.strimzi.io/v1beta2
    kind: KafkaUser
    metadata:
      name: kafka-xjoin
      labels:
        strimzi.io/cluster: ${KAFKA_CLUSTER}
    spec:
      authentication:
        type: scram-sha-512
      authorization:
        acls:
        # topics
        - resource:
            type: topic
            name: 'xjoin'
            patternType: prefix
          operation: All

        # connect offset, storage and config topics
        - resource:
            name: 'xjoin-connect'
            patternType: prefix
            type: topic
          operation: All

        # connect cluster consumer group
        - resource:
            name: ${GROUP_ID}
            patternType: literal
            type: group
          operation: All
        # connector consumer groups
        - resource:
            name: ${CONNECTOR_GROUP_PREFIX}
            patternType: prefix
            type: group
          operation: All
        type: simple